var lang = {
	en: {
		Mon: 'Mon',
		Tue: 'Tue',
		Wed: 'Wed',
		Thu: 'Thu',
		Fri: 'Fri',
		Sat: 'Sat',
		Sun: 'Sun',
		Monday: 'Monday',
		Tuesday: 'Tuesday',
		Wednesday: 'Wednesday',
		Thursday: 'Thursday',
		Friday: 'Friday',
		Saturday: 'Saturday',
		Sunday: 'Sunday',
		weather: 'Weather',
		updating: 'Updating',
		nodata: 'No data for this city!',
		error: 'There was an error! Retry in 30s.',
		offline: 'You are offline. Data can\'t be updated.',
		city: 'City',
		degrees: 'Degrees',
		refresh: 'Refresh interval',
		language: 'Language',
		redirect: 'Redirect to',
		format: 'Date format',
		reload: 'Reload now',
		options: 'Options',
		celsius: 'Celsius',
		fahrenheit: 'Fahrenheit',
		background: 'Background',
		textColor: 'Text color',
		main: 'Main',
		display: 'Display',
		hideLocation: 'Hide location',
		transitions: 'Transitions',
		transInterval: 'Interval',
		transHint: 'In \'Main\' section you can add more than one city by seperating<br> them with semicolon',
		hint: 'Hint',
		iconSet: 'Icon set',
		sec: 'sec.',
		transDuration: 'Duration',
		transType: 'Type',
		transFunc: 'Function',
		other: 'Other',
		cacheEnabled: 'Use image cache',
		clearCache: 'Clear cache',
		clear: 'Clear',
		resetDefault: 'Reset defaults',
		reset: 'Reset',
		transTypeNone: 'none',
		transTypeLeft: 'to left',
		transTypeRight: 'to right',
		transTypeOpacity: 'opacity'
	},
	cs: {
		Mon: 'Po',
		Tue: 'Út',
		Wed: 'St',
		Thu: 'Čt',
		Fri: 'Pá',
		Sat: 'So',
		Sun: 'Ne',
		Monday: 'Pondělí',
		Tuesday: 'Úterý',
		Wednesday: 'Středa',
		Thursday: 'Čtvrtek',
		Friday: 'Pátek',
		Saturday: 'Sobota',
		Sunday: 'Neděle',
		weather: 'Počasí',
		updating: 'Nahrávání',
		nodata: 'Žádné údaje pro zadané město!',
		error: 'Chyba při načítání! Další pokus za 30s.',
		offline: 'Jste offline. Data se nemohou načíst.',
		city: 'Město',
		degrees: 'Stupně',
		refresh: 'Interval nahrávání',
		language: 'Jazyk',
		redirect: 'Přesměrovat na',
		format: 'Formát data',
		reload: 'Načíst počasí',
		options: 'Nastavení',
		background: 'Pozadí',
		textColor: 'Barva textu',
		main: 'Hlavní',
		display: 'Zobrazení',
		hideLocation: 'Skrýt lokaci',
		transitions: 'Přechody',
		transInterval: 'Interval',
		transHint: 'V sekci \'Hlavní\' můžete zádat víc jak jedno město tím, že víc měst<br> oddělíte středníkem.',
		hint: 'Tip',
		iconSet: 'Typ ikon',
		sec: 'sek.',
		transDuration: 'Trvání',
		transType: 'Typ',
		transFunc: 'Funkce',
		other: 'Ostatní',
		cacheEnabled: 'Ukládat obrázky',
		clearCache: 'Vymazat úložiště',
		clear: 'Vymazat',
		resetDefault: 'Výchozí hodnoty',
		reset: 'Reset',
		transTypeNone: 'žádný',
		transTypeLeft: 'do leva',
		transTypeRight: 'do prava',
		transTypeOpacity: 'průhlednost'
	},
	de: {
		Mon: 'Mo',
		Tue: 'Di',
		Wed: 'Mi',
		Thu: 'Do',
		Fri: 'Fr',
		Sat: 'Sa',
		Sun: 'So',
		weather: 'Wetter',
		updating: 'Aktualisiere',
		nodata: 'Keine Daten für diesen Ort!',
		error: 'Fehler! Wiederholeung in 30s.',
		offline: 'Fehler! Aktualisierung der Daten nur online möglich.',
		city: 'Ort',
		degrees: 'Grad',
		refresh: 'Aktualisierung alle',
		language: 'Sprache',
		redirect: 'Zieladresse',
		format: 'Datumsformat',
		reload: 'Neu laden',
		options: 'Optionen',
		celsius: 'Celsius',
		fahrenheit: 'Fahrenheit',
		background: 'Hintergrund',
		textColor: 'Textfarbe',
		main: 'Hauptabschnitt',  /* 1 */ 
		display: 'Anzeige',
		hideLocation: 'Standort ausblenden',  
		transitions: 'Übergänge',
		transInterval: 'Intervall',
		transHint: 'Im Hauptabschnitt können sie mehrere, durch Semikolons<br>getrennte Orte einfügen.', 
		hint: 'Tipp',
		iconSet: 'Symbolsatz',
		sec: 'sek.'
	},
	sk: {
		Mon: 'Po',
		Tue: 'Ut',
		Wed: 'St',
		Thu: 'Št',
		Fri: 'Pi',
		Sat: 'So',
		Sun: 'Ne',
		Monday: 'Pondelok',
		Tuesday: 'Utorok',
		Wednesday: 'Streda',
		Thursday: 'Štvrtok',
		Friday: 'Piatok',
		Saturday: 'Sobota',
		Sunday: 'Nedeľa',
		weather: 'Počasie',
		updating: 'Načítanie',
		nodata: 'Žiadne údaje pre zadané mesto!', 
		error: 'Vyskytla sa chyba! Obnova za 30 sekúnd', 
		offline: 'Ste bez spojenia. Informácie nemôžu byť stiahnuté.', 
		city: 'Mesto', 
		degrees: 'Stupne', 
		refresh: 'Interval načítania', 
		language: 'Jazyk', 
		redirect: 'Presmerovať na', 
		format: 'Formát dátumu', 
		reload: 'Načitať počasie', 
		options: 'Nastavenie',
		background: 'Pozadie',
		textColor: 'Farba textu',
		main: 'Hlavné',
		display: 'Zobrazenie',
		hideLocation: 'Skryť lokáciu', 
		transitions: 'Prechody', 
		transInterval: 'Interval', 
		transHint: 'V \'Hlavné\' sekcií je možné pridať viac miest a oddeliť ich bodko-čiarkou', 
		hint: 'Tip',
		sec: 'sek.',
		transDuration: 'Trvanie', 
		transType: 'Typ', 
		transFunc: 'Funkcia', 
		other: 'Ďalšie', 
		cacheEnabled: 'Cache pre obrázky', 
		clearCache: 'Vymazať cache', 
		clear: 'Zmazať', 
		resetDefault: 'Zresetovať nastavenie', 
		reset: 'Reset'
	},
	fr: {
		Mon: 'Lun',
		Tue: 'Mar',
		Wed: 'Mer',
		Thu: 'Jeu',
		Fri: 'Ven',
		Sat: 'Sam',
		Sun: 'Dim',
		weather: 'Météo',
		updating: 'Updating',
		nodata: 'No data for this city!',
		error: 'There was an error! Retry in 30s.',
		offline: 'You are offline. Data can\'t be updated.'
	},
	hu: {
		Mon: 'Hét',
		Tue: 'Ked',
		Wed: 'Sze',
		Thu: 'Csü',
		Fri: 'Pén',
		Sat: 'Szo',
		Sun: 'Vas',
		weather: 'Időjárás',
		updating: 'Updating',
		nodata: 'No data for this city!',
		error: 'There was an error! Retry in 30s.',
		offline: 'You are offline. Data can\'t be updated.'
	},
	nl: {
		Mon: 'Maa',
		Tue: 'Din',
		Wed: 'Woe',
		Thu: 'Don',
		Fri: 'Vri',
		Sat: 'Zat',
		Sun: 'Zon',
		weather: 'Weer',
		updating: 'Updating',
		nodata: 'No data for this city!',
		error: 'There was an error! Retry in 30s.',
		offline: 'You are offline. Data can\'t be updated.'
	},
	no: {
		Mon: 'Man',
		Tue: 'Tir',
		Wed: 'Ons',
		Thu: 'Tor',
		Fri: 'Fre',
		Sat: 'Lør',
		Sun: 'Søn',
		weather: 'Vær',
		updating: 'Updating',
		nodata: 'No data for this city!',
		error: 'There was an error! Retry in 30s.',
		offline: 'You are offline. Data can\'t be updated.'
	},
	pl: {
		Mon: 'pon.',
		Tue: 'wt.',
		Wed: 'śr.',
		Thu: 'czw.',
		Fri: 'pt.',
		Sat: 'sob.',
		Sun: 'niedz.',
		Monday: 'poniedziałek',
		Tuesday: 'wtorek',
		Wednesday: 'środa',
		Thursday: 'czwartek',
		Friday: 'piątek',
		Saturday: 'sobota',
		Sunday: 'niedziela',
		weather: 'Pogoda',
		updating: 'Odświeżanie',
		nodata: 'Nie ma prognozy dla tego miasta.',
		error: 'Wystąpił błąd. Za 30 s ponowna próba.',
		offline: 'Nie ma połączenia z siecią, więc nie można odświeżyć danych.',
		city: 'Miasto',
		degrees: 'Skala',
		refresh: 'Odświeżaj co',
		language: 'Język',
		redirect: 'Kieruj do',
		format: 'Zapis daty',
		reload: 'Odśwież teraz',
		options: 'Ustawienia',
		celsius: 'Celsjusza',
		fahrenheit: 'Fahrenheita',
		background: 'Tło',
		textColor: 'Kolor tekstu',
		main: 'Ogólne',
		display: 'Wygląd',
		hideLocation: 'Ukryj nazwę miasta',
		transitions: 'Przejścia',
		transInterval: 'Międzyczas',
		transHint: 'Możesz wskazać więcej niż jedno miasto (w dziale "Ogólne")<br> rozdzielając nazwy średnikiem.',
		hint: 'Wskazówka',
		iconSet: 'Zestaw ikon',
		sec: 's',
		transDuration: 'Trwanie',
		transType: 'Sposób',
		transFunc: 'Funkcja',
		other: 'Inne',
		cacheEnabled: 'Zapamiętuj obrazki',
		clearCache: 'Wyczyść pamięć',
		clear: 'Usuń',
		resetDefault: 'Domyślne ustawienia',
		reset: 'Przywróć',
		transTypeNone: 'żaden',
		transTypeLeft: 'w lewo',
		transTypeRight: 'w prawo',
		transTypeOpacity: 'widoczność'
	},
	ru: {
		Mon: 'пон',
		Tue: 'вто',
		Wed: 'сре',
		Thu: 'чет',
		Fri: 'пят',
		Sat: 'суб',
		Sun: 'вос',
		weather: 'Погода',
		updating: 'Updating',
		nodata: 'No data for this city!',
		error: 'There was an error! Retry in 30s.',
		offline: 'You are offline. Data can\'t be updated.'
	},
	tr: {
		Mon: 'Pzt',
		Tue: 'Sal',
		Wed: 'Çar',
		Thu: 'Per',
		Fri: 'Cu',
		Sat: 'Cum',
		Sun: 'Paz',
		weather: 'Hava Durumu',
		updating: 'Güncelleştiriliyor',
		nodata: 'Bu şehir için bilgi yok!',
		error: 'Hata oluştu! 30 sn. içinde tekrar deneyin.',
		offline: 'Çevrimdışısınız. Bilgiler güncellenemedi.',
		city: 'Şehir',
		degrees: 'Derece',
		refresh: 'Yenileme sıklığı',
		language: 'Dil',
		redirect: 'Yönlendirme',
		format: 'Tarih Formatı',
		reload: 'Şimdi yenile',
		options: 'Tercihler',
		background: 'Arkaplan',
		textColor: 'Metin rengi',
		main: 'Ana sayfa',
		display: 'Görünüm',
		hideLocation: 'Konumu gizle',
		transitions: 'Geçişler',
		transInterval: 'Zaman aralığı',
		transHint: '\'Anasayfa\' bölümünden (noktalı virgül kullanarak) birden fazla<br>şehir ekleyebilirsiniz.',
		hint: 'İpucu',
		iconSet: 'Simge seti',
		sec: 'sn.',
		transDuration: 'Süre',
		transType: 'Tür',
		transFunc: 'Fonksiyon',
		other: 'Diğer',
		cacheEnabled: 'Resim ön belleğini kullan',
		clearCache: 'Ön belleği temizle',
		clear: 'Temizle',
		resetDefault: 'Varsayılana geri dön',
		reset: 'Sıfırla' 
	},
	uk: {
		Mon: 'пн',
		Tue: 'вт',
		Wed: 'ср',
		Thu: 'чт',
		Fri: 'пт',
		Sat: 'сб',
		Sun: 'нд',
		weather: 'Погода',
		updating: 'Оновлення',
		nodata: 'Немає відомостей для цього міста!',
		error: 'Сталася помилка! Спробуйте за 30с.',
		offline: 'Ви не в мережі. Неможливо завантажити дані.',
		city: 'Місто',
		degrees: 'Градуси',
		refresh: 'Інтервал оновлення',
		language: 'Мова',
		redirect: 'Перенаправляти на',
		format: 'Формат дати',
		reload: 'Перезавантажити зараз',
		options: 'Опції'
	},
	vi: {
		Mon: 'hai',
		Tue: 'ba',
		Wed: 'tư',
		Thu: 'năm',
		Fri: 'sáu',
		Sat: 'bảy',
		Sun: 'nhật',
		weather: 'Thời tiết',
		updating: 'Đang cập nhật',
		nodata: 'Không có dữ liệu về thành phố này!',
		error: 'Có lỗi xảy ra! Xin hãy thử lại trong 30 giây.',
		offline: 'Bạn không trực tuyến. Không thể cập nhật dữ liệu.',
		city: 'Thành phố',
		degrees: 'Nhiệt độ',
		refresh: 'khoảng thời gian',
		language: 'Ngôn ngữ',
		redirect: 'Gửi lại tới',
		format: 'Định dạng ngày',
		reload: 'Tải lại ngay',
		options: 'Tùy chọn',
		celsius: 'Độ C (°C)',
		fahrenheit: 'Độ F (⁰F)',
		background: 'Nền',
		textColor: 'Màu chữ',
		main: 'Trang chính',
		display: 'Hiển thị',
		hideLocation: 'Không hiển thị vị trí',
		transitions: 'Chuyển tiếp',
		transInterval: 'Khoảng cách',
		transHint: ' Ở phần \'Trang chính\' bạn có thể đưa thêm nhiều thành phố<br>bằng cách điền tên các thành phố đó vào và phân cách <br> chúng bằng dấu chấm phẩy (;)',
		hint: 'Gợi ý',
		iconSet: 'Biểu tượng',
		sec: 'giây',
		transDuration: 'Thời gian',
		transType: 'Kiểu',
		transFunc: 'Chức năng',
		other: 'Chức năng khác',
		cacheEnabled: 'Dùng hình ảnh lưu trữ',
		clearCache: 'Xóa nội dung lưu trữ',
		clear: 'Xóa',
		resetDefault: 'Khôi phục các cài đặt mặc định',
		reset: 'Khôi phục cài đặt'
	}
};

// LANG HANDLING

function dict(name) {
	return lang[widget.preferences.lang || 'en'][name] || lang.en[name] || 'translation error';
}


/*Localization updates ... not ready
(function() {
	var c = AJAX.create();
	var versionDay = '2011-02-08';
	var versionN = 1;
	function checkForUpdates() {
		c.getData('http://files.myopera.com/BS-Harou/WbW/version.txt', testVersion, handleLangError);
	}

	function testVersion(e) {
		var data = e.text.split('::');
		if (data.length === 2) {
			var d1 = new Date(versionDay);
			var d2 = new Date(data[0]);
			if (d1<d2 || (d1 == d2 && versionN < data[1] )) {
				alert('New version avalible');
				c.getData('http://files.myopera.com/BS-Harou/WbW/lang.json', loadLocalization, handleLangError);
			} else {
				// no new version
			}
		} else {
			// damm you my.opera.com for the confirm button :/
		}
	}

	function loadLocalization(e) {
		var data = e.text;
		if (JSON.isParseable(data)) {
			widget.preferences.localization = JSON.parse(e.text);
			setTimeout(checkForUpdates, 1000*60*120); // check again after two hours
		} else {
			console.log('Weather by Wundergdound: Localization file is corrupted.');
		}
	}

	function handleLangError(e) {
		console.log('Weather by WUnderground: Localization can\'t be updated!')
	}

	checkForUpdates();
}());
*/